# Workflow name
name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

# TODO actually build the component
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: install
        run: npm install

      - name: Build storybook
        run: npm run build-storybook

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./storybook-static